<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HSSSC1PCL01494" name="runner.ThirdTestRunner" tests="1" failures="0" timestamp="6 Jul 2017 11:39:09 GMT" time="70.891" errors="1">
  <testcase name="feature" time="70.891" classname="runner.ThirdTestRunner">
    <error type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: 
Expected: is &quot;You can&#039;t leave this empty..&quot;
     but: was &quot;You can&#039;t leave this empty.&quot;">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: 
Expected: is "You can't leave this empty.."
     but: was "You can't leave this empty."
	at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
	at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: 
Expected: is "You can't leave this empty.."
     but: was "You can't leave this empty."
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at steps.RegisterStep.assert_error_message_displays(RegisterStep.java:42)
	at âœ½.Then the error message display as below(src/test/java/features/Register3.feature:37)
]]>
    </error>
  </testcase> <!-- feature -->
</testsuite> <!-- runner.ThirdTestRunner -->
